# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend-and-server
labextension_name: nb_venv_kernels
project_short_description: Jupyterlab extension to detect notebook kernels similarly
    to how nb_conda_kernel does
python_name: nb_venv_kernels
repository: ''
test: true

